### ISSUE TITLE
Que es el tipo size_t y cuando se usa?

### ISSUE THREAD

**Issue by Anehg** [IIC2133-PUC/2024-2#4]
En los apuntes de intro-C, específicamente en la capsula de stucks el código de modelación edd.c donde se muestra una lista ligada hay un momento que al buscar cierto valor de un nodo de índice N, se usa un for especificando que el iterador es tipo size_t, mi pregunta es que significa ese size_t y cuando se usa, dejo a continuación un trozo del código mencionado:

![image](https://github.com/user-attachments/assets/d05204c0-4a6c-4876-a42c-a0b864f7e4de)

Gracias de antemano 😁✌️

**Comment by sebacarrascop** [comment]
El tipo size_t en C es un tipo de dato definido en la biblioteca estándar.

Se usa para representar tamaños de objetos en bytes y se garantiza que sea lo suficientemente grande como para contener el tamaño del objeto más grande que se puede gestionar. (Esto depende totalmente de la arquitectura del computador que estés usando ya sea de 32 o 64 bits)

La razón principal para usar size_t en lugar de un tipo de entero estándar como int es que size_t está específicamente diseñado para representar tamaños y índices de memoria. 

En resumen, usar size_t es una buena práctica para variables que representan tamaños o cantidades que no pueden ser negativas, como índices de arrays o listas. Pero de todas formas se pudo usar int y hubiera estado correcto.

Acá puedes encontrar más información si quieres ver más en profundidad sobre el tema: [stackoverflow](https://stackoverflow.com/questions/2550774/what-is-size-t-in-c)

**Comment by tomastrivino** [comment]
Como un heads up, las preguntas las puedes enviar en https://github.com/IIC2133-PUC/2024-2/discussions, que es el estándar ahora en el repositorio del curso.
